<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\Country;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        $tableName = (new Country)->getTable();
        if (Schema::hasTable($tableName)) {
            $rowCount = Country::count();
            if ($rowCount > 0) {
                Country::truncate();
            }
            DB::statement("ALTER TABLE $tableName AUTO_INCREMENT = 1;");
        }
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $countries = [
            [                
            "sortname" => "AF",
            "name" => "Afghanistan",
            "code" => "93",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "AL",
            "name" => "Albania",
            "code" => "355",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "DZ",
            "name" => "Algeria",
            "code" => "213",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "AS",
            "name" => "American Samoa",
            "code" => "1684",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "AD",
            "name" => "Andorra",
            "code" => "376",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "AO",
            "name" => "Angola",
            "code" => "244",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "AI",
            "name" => "Anguilla",
            "code" => "1264",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "AQ",
            "name" => "Antarctica",
            "code" => "0",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "AG",
            "name" => "Antigua And Barbuda",
            "code" => "1268",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "AR",
            "name" => "Argentina",
            "code" => "54",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "AM",
            "name" => "Armenia",
            "code" => "374",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "AW",
            "name" => "Aruba",
            "code" => "297",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "AU",
            "name" => "Australia",
            "code" => "61",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "AT",
            "name" => "Austria",
            "code" => "43",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "AZ",
            "name" => "Azerbaijan",
            "code" => "994",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "BS",
            "name" => "Bahamas The",
            "code" => "1242",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "BH",
            "name" => "Bahrain",
            "code" => "973",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "BD",
            "name" => "Bangladesh",
            "code" => "880",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "BB",
            "name" => "Barbados",
            "code" => "1246",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "BY",
            "name" => "Belarus",
            "code" => "375",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "BE",
            "name" => "Belgium",
            "code" => "32",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "BZ",
            "name" => "Belize",
            "code" => "501",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "BJ",
            "name" => "Benin",
            "code" => "229",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "BM",
            "name" => "Bermuda",
            "code" => "1441",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "BT",
            "name" => "Bhutan",
            "code" => "975",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "BO",
            "name" => "Bolivia",
            "code" => "591",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "BA",
            "name" => "Bosnia and Herzegovina",
            "code" => "387",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "BW",
            "name" => "Botswana",
            "code" => "267",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "BV",
            "name" => "Bouvet Island",
            "code" => "0",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "BR",
            "name" => "Brazil",
            "code" => "55",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "IO",
            "name" => "British Indian Ocean Territory",
            "code" => "246",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "BN",
            "name" => "Brunei",
            "code" => "673",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "BG",
            "name" => "Bulgaria",
            "code" => "359",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "BF",
            "name" => "Burkina Faso",
            "code" => "226",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "BI",
            "name" => "Burundi",
            "code" => "257",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "KH",
            "name" => "Cambodia",
            "code" => "855",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "CM",
            "name" => "Cameroon",
            "code" => "237",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "CA",
            "name" => "Canada",
            "code" => "1",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "CV",
            "name" => "Cape Verde",
            "code" => "238",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "KY",
            "name" => "Cayman Islands",
            "code" => "1345",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "CF",
            "name" => "Central African Republic",
            "code" => "236",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "TD",
            "name" => "Chad",
            "code" => "235",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "CL",
            "name" => "Chile",
            "code" => "56",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "CN",
            "name" => "China",
            "code" => "86",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "CX",
            "name" => "Christmas Island",
            "code" => "61",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "CC",
            "name" => "Cocos (Keeling) Islands",
            "code" => "672",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "CO",
            "name" => "Colombia",
            "code" => "57",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "KM",
            "name" => "Comoros",
            "code" => "269",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "CG",
            "name" => "Republic Of The Congo",
            "code" => "242",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "CD",
            "name" => "Democratic Republic Of The Congo",
            "code" => "242",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "CK",
            "name" => "Cook Islands",
            "code" => "682",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "CR",
            "name" => "Costa Rica",
            "code" => "506",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "CI",
            "name" => "Cote D''Ivoire (Ivory Coast)",
            "code" => "225",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "HR",
            "name" => "Croatia (Hrvatska)",
            "code" => "385",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "CU",
            "name" => "Cuba",
            "code" => "53",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "CY",
            "name" => "Cyprus",
            "code" => "357",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "CZ",
            "name" => "Czech Republic",
            "code" => "420",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "DK",
            "name" => "Denmark",
            "code" => "45",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "DJ",
            "name" => "Djibouti",
            "code" => "253",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "DM",
            "name" => "Dominica",
            "code" => "1767",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "DO",
            "name" => "Dominican Republic",
            "code" => "1809",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "TP",
            "name" => "East Timor",
            "code" => "670",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "EC",
            "name" => "Ecuador",
            "code" => "593",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "EG",
            "name" => "Egypt",
            "code" => "20",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "SV",
            "name" => "El Salvador",
            "code" => "503",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "GQ",
            "name" => "Equatorial Guinea",
            "code" => "240",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "ER",
            "name" => "Eritrea",
            "code" => "291",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "EE",
            "name" => "Estonia",
            "code" => "372",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "ET",
            "name" => "Ethiopia",
            "code" => "251",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "XA",
            "name" => "External Territories of Australia",
            "code" => "61",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "FK",
            "name" => "Falkland Islands",
            "code" => "500",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "FO",
            "name" => "Faroe Islands",
            "code" => "298",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "FJ",
            "name" => "Fiji Islands",
            "code" => "679",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "FI",
            "name" => "Finland",
            "code" => "358",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "FR",
            "name" => "France",
            "code" => "33",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "GF",
            "name" => "French Guiana",
            "code" => "594",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "PF",
            "name" => "French Polynesia",
            "code" => "689",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "TF",
            "name" => "French Southern Territories",
            "code" => "0",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "GA",
            "name" => "Gabon",
            "code" => "241",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "GM",
            "name" => "Gambia The",
            "code" => "220",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "GE",
            "name" => "Georgia",
            "code" => "995",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "DE",
            "name" => "Germany",
            "code" => "49",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "GH",
            "name" => "Ghana",
            "code" => "233",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "GI",
            "name" => "Gibraltar",
            "code" => "350",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "GR",
            "name" => "Greece",
            "code" => "30",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "GL",
            "name" => "Greenland",
            "code" => "299",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "GD",
            "name" => "Grenada",
            "code" => "1473",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "GP",
            "name" => "Guadeloupe",
            "code" => "590",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "GU",
            "name" => "Guam",
            "code" => "1671",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "GT",
            "name" => "Guatemala",
            "code" => "502",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "XU",
            "name" => "Guernsey and Alderney",
            "code" => "44",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "GN",
            "name" => "Guinea",
            "code" => "224",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "GW",
            "name" => "Guinea-Bissau",
            "code" => "245",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "GY",
            "name" => "Guyana",
            "code" => "592",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "HT",
            "name" => "Haiti",
            "code" => "509",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "HM",
            "name" => "Heard and McDonald Islands",
            "code" => "0",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "HN",
            "name" => "Honduras",
            "code" => "504",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "HK",
            "name" => "Hong Kong S.A.R.",
            "code" => "852",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "HU",
            "name" => "Hungary",
            "code" => "36",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "IS",
            "name" => "Iceland",
            "code" => "354",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "IN",
            "name" => "India",
            "code" => "91",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "ID",
            "name" => "Indonesia",
            "code" => "62",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "IR",
            "name" => "Iran",
            "code" => "98",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "IQ",
            "name" => "Iraq",
            "code" => "964",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "IE",
            "name" => "Ireland",
            "code" => "353",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "IL",
            "name" => "Israel",
            "code" => "972",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "IT",
            "name" => "Italy",
            "code" => "39",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "JM",
            "name" => "Jamaica",
            "code" => "1876",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "JP",
            "name" => "Japan",
            "code" => "81",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "XJ",
            "name" => "Jersey",
            "code" => "44",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "JO",
            "name" => "Jordan",
            "code" => "962",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "KZ",
            "name" => "Kazakhstan",
            "code" => "7",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "KE",
            "name" => "Kenya",
            "code" => "254",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "KI",
            "name" => "Kiribati",
            "code" => "686",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "KP",
            "name" => "Korea North",
            "code" => "850",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "KR",
            "name" => "Korea South",
            "code" => "82",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "KW",
            "name" => "Kuwait",
            "code" => "965",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "KG",
            "name" => "Kyrgyzstan",
            "code" => "996",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "LA",
            "name" => "Laos",
            "code" => "856",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "LV",
            "name" => "Latvia",
            "code" => "371",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "LB",
            "name" => "Lebanon",
            "code" => "961",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "LS",
            "name" => "Lesotho",
            "code" => "266",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "LR",
            "name" => "Liberia",
            "code" => "231",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "LY",
            "name" => "Libya",
            "code" => "218",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "LI",
            "name" => "Liechtenstein",
            "code" => "423",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "LT",
            "name" => "Lithuania",
            "code" => "370",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "LU",
            "name" => "Luxembourg",
            "code" => "352",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "MO",
            "name" => "Macau S.A.R.",
            "code" => "853",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "MK",
            "name" => "Macedonia",
            "code" => "389",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "MG",
            "name" => "Madagascar",
            "code" => "261",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "MW",
            "name" => "Malawi",
            "code" => "265",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "MY",
            "name" => "Malaysia",
            "code" => "60",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "MV",
            "name" => "Maldives",
            "code" => "960",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "ML",
            "name" => "Mali",
            "code" => "223",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "MT",
            "name" => "Malta",
            "code" => "356",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "XM",
            "name" => "Man (Isle of)",
            "code" => "44",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "MH",
            "name" => "Marshall Islands",
            "code" => "692",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "MQ",
            "name" => "Martinique",
            "code" => "596",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "MR",
            "name" => "Mauritania",
            "code" => "222",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "MU",
            "name" => "Mauritius",
            "code" => "230",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "YT",
            "name" => "Mayotte",
            "code" => "269",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "MX",
            "name" => "Mexico",
            "code" => "52",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "FM",
            "name" => "Micronesia",
            "code" => "691",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "MD",
            "name" => "Moldova",
            "code" => "373",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "MC",
            "name" => "Monaco",
            "code" => "377",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "MN",
            "name" => "Mongolia",
            "code" => "976",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "MS",
            "name" => "Montserrat",
            "code" => "1664",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "MA",
            "name" => "Morocco",
            "code" => "212",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "MZ",
            "name" => "Mozambique",
            "code" => "258",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "MM",
            "name" => "Myanmar",
            "code" => "95",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "NA",
            "name" => "Namibia",
            "code" => "264",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "NR",
            "name" => "Nauru",
            "code" => "674",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "NP",
            "name" => "Nepal",
            "code" => "977",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "AN",
            "name" => "Netherlands Antilles",
            "code" => "599",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "NL",
            "name" => "Netherlands The",
            "code" => "31",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "NC",
            "name" => "New Caledonia",
            "code" => "687",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "NZ",
            "name" => "New Zealand",
            "code" => "64",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "NI",
            "name" => "Nicaragua",
            "code" => "505",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "NE",
            "name" => "Niger",
            "code" => "227",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "NG",
            "name" => "Nigeria",
            "code" => "234",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "NU",
            "name" => "Niue",
            "code" => "683",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "NF",
            "name" => "Norfolk Island",
            "code" => "672",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "MP",
            "name" => "Northern Mariana Islands",
            "code" => "1670",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "NO",
            "name" => "Norway",
            "code" => "47",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "OM",
            "name" => "Oman",
            "code" => "968",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "PK",
            "name" => "Pakistan",
            "code" => "92",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "PW",
            "name" => "Palau",
            "code" => "680",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "PS",
            "name" => "Palestinian Territory Occupied",
            "code" => "970",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "PA",
            "name" => "Panama",
            "code" => "507",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "PG",
            "name" => "Papua new Guinea",
            "code" => "675",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "PY",
            "name" => "Paraguay",
            "code" => "595",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "PE",
            "name" => "Peru",
            "code" => "51",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "PH",
            "name" => "Philippines",
            "code" => "63",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "PN",
            "name" => "Pitcairn Island",
            "code" => "0",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "PL",
            "name" => "Poland",
            "code" => "48",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "PT",
            "name" => "Portugal",
            "code" => "351",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "PR",
            "name" => "Puerto Rico",
            "code" => "1787",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "QA",
            "name" => "Qatar",
            "code" => "974",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "RE",
            "name" => "Reunion",
            "code" => "262",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "RO",
            "name" => "Romania",
            "code" => "40",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "RU",
            "name" => "Russia",
            "code" => "70",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "RW",
            "name" => "Rwanda",
            "code" => "250",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "SH",
            "name" => "Saint Helena",
            "code" => "290",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "KN",
            "name" => "Saint Kitts And Nevis",
            "code" => "1869",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "LC",
            "name" => "Saint Lucia",
            "code" => "1758",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "PM",
            "name" => "Saint Pierre and Miquelon",
            "code" => "508",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "VC",
            "name" => "Saint Vincent And The Grenadines",
            "code" => "1784",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "WS",
            "name" => "Samoa",
            "code" => "684",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "SM",
            "name" => "San Marino",
            "code" => "378",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "ST",
            "name" => "Sao Tome and Principe",
            "code" => "239",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "SA",
            "name" => "Saudi Arabia",
            "code" => "966",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "SN",
            "name" => "Senegal",
            "code" => "221",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "RS",
            "name" => "Serbia",
            "code" => "381",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "SC",
            "name" => "Seychelles",
            "code" => "248",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "SL",
            "name" => "Sierra Leone",
            "code" => "232",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "SG",
            "name" => "Singapore",
            "code" => "65",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "SK",
            "name" => "Slovakia",
            "code" => "421",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "SI",
            "name" => "Slovenia",
            "code" => "386",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "XG",
            "name" => "Smaller Territories of the UK",
            "code" => "44",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "SB",
            "name" => "Solomon Islands",
            "code" => "677",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "SO",
            "name" => "Somalia",
            "code" => "252",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "ZA",
            "name" => "South Africa",
            "code" => "27",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "GS",
            "name" => "South Georgia",
            "code" => "0",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "SS",
            "name" => "South Sudan",
            "code" => "211",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "ES",
            "name" => "Spain",
            "code" => "34",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "LK",
            "name" => "Sri Lanka",
            "code" => "94",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "SD",
            "name" => "Sudan",
            "code" => "249",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "SR",
            "name" => "Suriname",
            "code" => "597",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "SJ",
            "name" => "Svalbard And Jan Mayen Islands",
            "code" => "47",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "SZ",
            "name" => "Swaziland",
            "code" => "268",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "SE",
            "name" => "Sweden",
            "code" => "46",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "CH",
            "name" => "Switzerland",
            "code" => "41",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "SY",
            "name" => "Syria",
            "code" => "963",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "TW",
            "name" => "Taiwan",
            "code" => "886",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "TJ",
            "name" => "Tajikistan",
            "code" => "992",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "TZ",
            "name" => "Tanzania",
            "code" => "255",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "TH",
            "name" => "Thailand",
            "code" => "66",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "TG",
            "name" => "Togo",
            "code" => "228",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "TK",
            "name" => "Tokelau",
            "code" => "690",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "TO",
            "name" => "Tonga",
            "code" => "676",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "TT",
            "name" => "Trinidad And Tobago",
            "code" => "1868",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "TN",
            "name" => "Tunisia",
            "code" => "216",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "TR",
            "name" => "Turkey",
            "code" => "90",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "TM",
            "name" => "Turkmenistan",
            "code" => "7370",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "TC",
            "name" => "Turks And Caicos Islands",
            "code" => "1649",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "TV",
            "name" => "Tuvalu",
            "code" => "688",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "UG",
            "name" => "Uganda",
            "code" => "256",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "UA",
            "name" => "Ukraine",
            "code" => "380",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "AE",
            "name" => "United Arab Emirates",
            "code" => "971",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "GB",
            "name" => "United Kingdom",
            "code" => "44",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "US",
            "name" => "United States",
            "code" => "1",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "UM",
            "name" => "United States Minor Outlying Islands",
            "code" => "1",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "UY",
            "name" => "Uruguay",
            "code" => "598",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "UZ",
            "name" => "Uzbekistan",
            "code" => "998",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "VU",
            "name" => "Vanuatu",
            "code" => "678",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "VA",
            "name" => "Vatican City State (Holy See)",
            "code" => "39",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "VE",
            "name" => "Venezuela",
            "code" => "58",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "VN",
            "name" => "Vietnam",
            "code" => "84",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "VG",
            "name" => "Virgin Islands (British)",
            "code" => "1284",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "VI",
            "name" => "Virgin Islands (US)",
            "code" => "1340",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "WF",
            "name" => "Wallis And Futuna Islands",
            "code" => "681",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "EH",
            "name" => "Western Sahara",
            "code" => "212",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "YE",
            "name" => "Yemen",
            "code" => "967",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "YU",
            "name" => "Yugoslavia",
            "code" => "38",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "ZM",
            "name" => "Zambia",
            "code" => "260",
            "created_at" => now(),
            "updated_at" => now(),
            ],
            [                
            "sortname" => "ZW",
            "name" => "Zimbabwe",
            "code" => "26",
            "created_at" => now(),
            "updated_at" => now(),
            ]
        ];

        Country::insert($countries);
    }
}
